name: mmdate
description: Algorithm, Myanmar Date
version: 1.0.0
homepage: https://kohtut.dev/
author: 
  - Ko Htut

dependencies:
 path: ^1.6.0

environment:
  sdk: '>=1.19.0 <3.0.0'
  flutter: ^0.1.2
