name: mmdate
description: Algorithm, Program and Calculation of Myanmar Date
version: 1.0.21
homepage: https://kohtut.dev/
# publish_to: none
# author: 
#   - Ko Htut

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
