name: mmdate
description: Algorithm, Program and Calculation of Myanmar Date 
version: 1.0.3
homepage: https://github.com/ko-htut/MMDate
# publish_to: none
# author: 
#   - Ko Htut

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter